#!/usr/bin/env python3
"""Generate C fixtures for the VectiLicense core test.

Independent reimplementation of the payload/fingerprint/base32 rules from the
spec — if the C and this disagree, one of them is wrong, which is the point.
"""
import hashlib, os, struct
from cryptography.hazmat.primitives.asymmetric.ed25519 import Ed25519PrivateKey
from cryptography.hazmat.primitives import serialization

ALPHA = "0123456789ABCDEFGHJKMNPQRSTVWXYZ"

def b32(data: bytes) -> str:
    bits = "".join(f"{b:08b}" for b in data)
    bits += "0" * ((-len(bits)) % 5)
    return "".join(ALPHA[int(bits[i:i+5], 2)] for i in range(0, len(bits), 5))

FP_DOMAIN = b"vectilicense:fingerprint:v1"
SIGN_PREFIX = b"vectilicense:v1"

# The fake HAL in the test yields exactly these segments, in this order.
SEGMENTS = [b"\xde\xad\xbe\xef\x00\x11", b"vecti-test-board", b""]

def fingerprint(segments):
    h = hashlib.sha256()
    h.update(FP_DOMAIN)
    for s in segments:
        assert len(s) < 256
        h.update(bytes([len(s)]))
        h.update(s)
    return h.digest()

def payload(key_id, family, features, device_id16, nb, na, serial):
    return (bytes([0x56, 0x01, key_id, family])
            + struct.pack("<I", features)
            + device_id16
            + struct.pack("<I", nb)
            + struct.pack("<I", na)
            + struct.pack("<I", serial))

def carr(name, data):
    body = ",".join(f"0x{b:02x}" for b in data)
    return f"static const uint8_t {name}[{len(data)}] = {{{body}}};\n"

# Deterministic key so the fixture is reproducible.
seed = hashlib.sha256(b"vectilicense test key, not a real one").digest()
sk = Ed25519PrivateKey.from_private_bytes(seed)
pk = sk.public_key().public_bytes(serialization.Encoding.Raw,
                                  serialization.PublicFormat.Raw)

fp = fingerprint(SEGMENTS)
dev = fp[:16]

out = ["/* GENERATED by tests/gen_fixtures.py — do not edit by hand. */\n",
       "#ifndef VL_TEST_FIXTURES_H\n#define VL_TEST_FIXTURES_H\n#include <stdint.h>\n\n"]
out.append(carr("FIX_PUBKEY", pk))
out.append(carr("FIX_FINGERPRINT", fp))
out.append(f'static const char FIX_DEVICE_ID_STR[] = "{b32(dev)}";\n')

cases = {
    # name           key_id family features  nb          na          serial
    "PERPETUAL":     (7, 0x02, 0x0000000d, 0,          0,          1001),
    "WINDOWED":      (7, 0x02, 0x00000001, 1700000000, 1800000000, 1002),
    "EXPIRED":       (7, 0x02, 0x00000001, 0,          1600000000, 1003),
    "FUTURE":        (7, 0x02, 0x00000001, 1900000000, 0,          1004),
    "REVOKED":       (7, 0x02, 0x00000001, 0,          0,          4242),
    "WRONGFAMILY":   (7, 0x03, 0x00000001, 0,          0,          1005),
    "UNKNOWNKEY":    (9, 0x02, 0x00000001, 0,          0,          1006),
}
for name, (kid, fam, feat, nb, na, ser) in cases.items():
    p = payload(kid, fam, feat, dev, nb, na, ser)
    sig = sk.sign(SIGN_PREFIX + b"\x00" + p)
    out.append(f'static const char FIX_BLOB_{name}[] = "{b32(p + sig)}";\n')

# Same payload as PERPETUAL but bound to a different device.
other = hashlib.sha256(b"some other device").digest()[:16]
p = payload(7, 0x02, 1, other, 0, 0, 1007)
out.append(f'static const char FIX_BLOB_OTHERDEV[] = "{b32(p + sk.sign(SIGN_PREFIX + chr(0).encode() + p))}";\n')

# Correctly-signed payload, but signed over the payload WITHOUT the domain
# prefix — proves the domain separation is actually covered.
p = payload(7, 0x02, 1, dev, 0, 0, 1008)
out.append(f'static const char FIX_BLOB_NODOMAIN[] = "{b32(p + sk.sign(p))}";\n')

out.append("\n#endif\n")
here = os.path.dirname(os.path.abspath(__file__))
open(os.path.join(here, "vl_test_fixtures.h"), "w").writelines(out)
print("device id:", b32(dev))
print("pubkey:", pk.hex())
print("blob len:", len(b32(payload(7,2,1,dev,0,0,1))) + 160 - 160)
